notebook:
	jupyter nbconvert --to=notebook --inplace --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=0 colbert-fallon-ratings.ipynb

gist:
	gist --update https://gist.github.com/AlJohri/8ff27d47bc73b68ed80ec66c44deb446 colbert-fallon-ratings.ipynb
	open https://gist.github.com/AlJohri/8ff27d47bc73b68ed80ec66c44deb446
